apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name}}-node
  namespace: {{ .Release.Namespace}}
spec:
  type: NodePort
  selector:
{{ include "selector.labels" . | indent 4}}
  ports:
    - protocol: TCP
      port: 8090          # expose or external or service port
      targetPort: 8090  #container port
      nodePort: 30023
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name}}-cluster
  namespace: {{ .Release.Namespace}}
spec:
  type: ClusterIP
  selector:
{{ include "selector.labels" . | indent 4}}
  ports:
    - protocol: TCP
      port: 8090          # expose or external or service port
      targetPort: 8090  #container port
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name}}-lb
  namespace: {{ .Release.Namespace}}
spec:
  type: LoadBalancer
  selector:
{{ include "selector.labels" . | indent 4}}
  ports:
    - protocol: TCP
      port: 8090          # expose or external or service port
      targetPort: 8090  #container port      